from fpdf import FPDF
from datetime import datetime

def generate_report(module_name, data, chart_b64=None):
    try:
        pdf = FPDF(orientation='P', unit='mm', format='A4')
        pdf.set_margins(15, 15, 15)
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Header background
        pdf.set_fill_color(13, 20, 39)
        pdf.rect(0, 0, 210, 40, 'F')

        # Title
        pdf.set_xy(15, 8)
        pdf.set_font('Arial', 'B', 18)
        pdf.set_text_color(79, 195, 247)
        pdf.cell(180, 10, 'CyberTrace', ln=True, align='C')

        pdf.set_xy(15, 20)
        pdf.set_font('Arial', '', 10)
        pdf.set_text_color(200, 220, 240)
        pdf.cell(180, 8, 'Digital Evidence Analyzer |', ln=True, align='C')

        pdf.set_xy(15, 30)
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(150, 180, 200)
        pdf.cell(180, 8, 'Developed by Sneha Dogra | B.Tech CSE (CY)', ln=True, align='C')

        pdf.set_y(50)

        # Module name box
        pdf.set_fill_color(220, 235, 250)
        pdf.set_text_color(20, 60, 120)
        pdf.set_font('Arial', 'B', 13)
        pdf.cell(180, 10, f'  Module: {module_name}', ln=True, fill=True)
        pdf.ln(3)

        # Metadata
        pdf.set_font('Arial', '', 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(180, 6, f'Generated: {datetime.now().strftime("%d-%m-%Y %H:%M:%S")}', ln=True)
        pdf.cell(180, 6, 'Analyst: Sneha Dogra | Cyber Police Station Jammu', ln=True)
        pdf.ln(5)

        # Divider line
        pdf.set_draw_color(79, 195, 247)
        pdf.set_line_width(0.8)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(6)

        # Findings header
        pdf.set_font('Arial', 'B', 11)
        pdf.set_text_color(20, 60, 120)
        pdf.cell(180, 8, 'FINDINGS', ln=True)
        pdf.ln(2)

        # Data rows alternating background
        colors = [(240, 245, 255), (255, 255, 255)]
        i = 0
        for key, value in data.items():
            if value is None:
                value = 'N/A'
            label = str(key).replace('_', ' ').upper()
            val = str(value)

            # Row background
            pdf.set_fill_color(*colors[i % 2])
            pdf.set_text_color(60, 80, 120)
            pdf.set_font('Arial', 'B', 9)
            pdf.cell(55, 8, f'  {label}', border=0, fill=True)

            pdf.set_text_color(30, 30, 30)
            pdf.set_font('Arial', '', 9)
            # Use write instead of cell to avoid overflow
            x = pdf.get_x()
            y = pdf.get_y()
            pdf.set_xy(x, y)
            pdf.cell(125, 8, val[:80], border=0, fill=True, ln=True)
            i += 1

        pdf.ln(8)

        # Footer line
        pdf.set_draw_color(79, 195, 247)
        pdf.set_line_width(0.5)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(4)

        pdf.set_font('Arial', 'I', 8)
        pdf.set_text_color(150, 150, 150)
        pdf.cell(180, 6, 'This report was generated by CyberTrace | Confidential |', ln=True, align='C')

        return bytes(pdf.output())

    except Exception as e:
        print(f"PDF ERROR: {str(e)}")
        return None